### ISSUE TITLE
dead code in ZRtp.cpp

### ISSUE THREAD

**Issue by jresende** [wernerd/ZRTPCPP#29]
why is this code from file ZRtp.cpp:
`if (signSasSeen && signatureLength > 0 && confirm1->isSignatureLengthOk()) 
...
 callback->checkSASSignature(sasHash)
`
to call the callback if in this place you don't have the sas? this is necessary?

**Comment by wernerd** [comment]
There are two places in the code that call back to checkSASSignature. In both places the sasHash is already available.

**Comment by jresende** [comment]
but I think that the code never enter in that if. when you write signatureLength is what signature?

**Comment by wernerd** [comment]
Obviously this code is entered only if the caller (the application) sets and uses the sign SAS feature. Refer to the ZRTP spec RFC 6189, section 7.2
