### ISSUE TITLE
Can't make the project : DEPRECATED does not name a type

### ISSUE THREAD

**Issue by patricia93sousa** [wernerd/ZRTPCPP#35]
I'm trying to make the project but I get the following error:

> In file included from /home/patriciarvsousa/work/ZRTPCPP/clients/ccrtp/ZrtpQueue.cpp:25:0:
> /home/patriciarvsousa/work/ZRTPCPP/clients/ccrtp/ZrtpQueue.h:433:5: error: ‘DEPRECATED’ does not name a type
>      DEPRECATED std::string getMultiStrParams() {return getMultiStrParams(NULL); }
>      ^
> /home/patriciarvsousa/work/ZRTPCPP/clients/ccrtp/ZrtpQueue.h:453:5: error: ‘DEPRECATED’ does not name a type
>      DEPRECATED void setMultiStrParams(std::string parameters) { setMultiStrParams(parameters, NULL);}
>      ^
> clients/ccrtp/CMakeFiles/zrtpcpp.dir/build.make:758: recipe for target 'clients/ccrtp/CMakeFiles/zrtpcpp.dir/ZrtpQueue.cpp.o' failed
> make[2]: *** [clients/ccrtp/CMakeFiles/zrtpcpp.dir/ZrtpQueue.cpp.o] Error 1
> CMakeFiles/Makefile2:121: recipe for target 'clients/ccrtp/CMakeFiles/zrtpcpp.dir/all' failed
> make[1]: *** [clients/ccrtp/CMakeFiles/zrtpcpp.dir/all] Error 2
> Makefile:149: recipe for t

**Comment by jose1711** [comment]
same problem - arch linux 64bit, gcc version 6.3.1 20170109 (GCC)

**Comment by wernerd** [comment]
Thanks for the report. Due to some name conficts I renamed 'DEPRECATED' to 'DEPRECATED_ZRTP' and it seem that I missed to fix it in ZrtpQueue source files. I'll fix that in the next days, until then please just fix the name. Thanks.
