### ISSUE TITLE
Memory leak during processing ZrtpMessage

### ISSUE THREAD

**Issue by oleksandr-vovk** [wernerd/ZRTPCPP#50]
Memory leak was detected using Valgrind-3.19.0 
`==550626== 552 bytes in 1 blocks are definitely lost in loss record 104 of 110`
`==550626==    at 0x4C378C3: operator new(unsigned long) (vg_replace_malloc.c:422)`
`==550626==    by 0x5EEDDEF: ??? (in /usr/lib64/libzrtpcpp.so.4.4.0)`
`==550626==    by 0x5EDBB8C: ZRtp::prepareCommit(ZrtpPacketHello*, unsigned int*) (in /usr/lib64/libzrtpcpp.so.4.4.0)`
`==550626==    by 0x5EE2833: ZrtpStateClass::evDetect() (in /usr/lib64/libzrtpcpp.so.4.4.0)`
`==550626==    by 0x5EE22F9: ZrtpStateClass::processEvent(Event*) (in /usr/lib64/libzrtpcpp.so.4.4.0)`
`==550626==    by 0x5ED848E: ZRtp::processZrtpMessage(unsigned char*, unsigned int, unsigned long) (in /usr/lib64/libzrtpcpp.so.4.4.0)`

**Comment by oleksandr-vovk** [comment]
Hello @wernerd!
Please, bring your attention to this issue and share your feedback.

Thank you.

**Comment by wernerd** [comment]
Hi Oleksandr, according to the output it seems that this is a version 4.4.0. This version is quite old, the current version is 4.7.0 in master branch. This version contains several updates, for example using smart pointers instead of new/delete or alike.

**Comment by oleksandr-vovk** [comment]
Thanks. The issue is not observable on the newer versions (e.g. 4.6.6).
